name: install

env:
  MAAFW_VERSION: ""
  MFAA_VERSION: ""
  MXU_VERSION: ""

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.1"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi

          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          is_prerelease=false
          if [[ $tag =~ .*alpha.* || $tag =~ .*beta.* || $tag =~ .*rc.* || $tag =~ .*dev.* || $tag =~ .*-ci.* ]]; then
            is_prerelease=true
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
          echo is_prerelease=$is_prerelease | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}
      is_prerelease: ${{ steps.set_tag.outputs.is_prerelease }}

  install:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-${{ matrix.os }}-${{ matrix.arch }}*"
          latest: ${{ env.MAAFW_VERSION == '' }}
          tag: ${{ env.MAAFW_VERSION }}
          out-file-path: "deps"
          extract: true

      - name: Download MFAAvalonia
        id: download_mfa
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAAvalonia
          fileName: "MFAAvalonia-*-${{ (matrix.os == 'win' && 'win') || (matrix.os == 'macos' && 'osx') || (matrix.os == 'linux' && 'linux') }}-${{ (matrix.arch == 'x86_64' && 'x64') || (matrix.arch == 'aarch64' && 'arm64') }}*"
          latest: ${{ env.MFAA_VERSION == '' }}
          tag: ${{ env.MFAA_VERSION }}
          out-file-path: "MFAA"
          extract: true

      - name: Download MXU
        id: download_mxu
        uses: robinraju/release-downloader@v1
        with:
          repository: MistEO/MXU
          fileName: "MXU-${{ matrix.os }}-${{ matrix.arch }}*"
          latest: ${{ env.MXU_VERSION == '' }}
          tag: ${{ env.MXU_VERSION }}
          out-file-path: "MXU"
          extract: true
          
      - name: Remove built-in runtimes
        shell: bash
        run: |
          rm -rf MFAA/runtimes
          rm -rf MXU/runtimes

      - name: Build MFAA Package
        shell: bash
        run: |
          cd tools/
          python -m pip install -r ./requirements.txt
          python ./install_mfaa.py ${{ needs.meta.outputs.tag }} ${{ matrix.os }} ${{ matrix.arch }}
          cd ..

      - name: Build MXU Package
        shell: bash
        run: |
          cd tools/
          python ./install_mxu.py ${{ needs.meta.outputs.tag }} ${{ matrix.os }} ${{ matrix.arch }}
          cd ..

      # 分開上傳兩個 Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: MFAAvalonia-PCR-${{ matrix.os }}-${{ matrix.arch }}-MFAA
          path: "install-mfaa"

      - uses: actions/upload-artifact@v4
        with:
          name: MFAAvalonia-PCR-${{ matrix.os }}-${{ matrix.arch }}-MXU
          path: "install-mxu"

  changelog:
    name: Generate changelog
    needs: meta
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: >-
            -vv --latest --strip header
            ${{ needs.meta.outputs.is_prerelease == 'false' && '--tag-pattern "^v[0-9]+\\.[0-9]+\\.[0-9]+$"' || '' }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, install, changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            if [ -d "$f" ]; then
              (cd "$f" && zip -r "../$f-${{ needs.meta.outputs.tag }}.zip" .)
            fi
          done

      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*.zip
          tag_name: ${{ needs.meta.outputs.tag }}
          body: ${{ needs.changelog.outputs.release_body }}
          draft: false
          prerelease: ${{ needs.meta.outputs.is_prerelease == 'true' }}